#!/bin/bash

if [ -z "$SAFE_ADDR" ]; then
    echo ' must set SAFE_ADDR env '
    exit 1
fi


postInstance() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID,?ImageStoreOwner
    curl -XPOST $SAFE_ADDR/postInstance -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"]}"
}
delInstance() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstance -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"]}"
}
        

postVMInstance() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID,?Cidr,?ImageStoreOwner,?Vpc
    curl -XPOST $SAFE_ADDR/postVMInstance -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\"]}"
}
delVMInstance() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVMInstance -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\"]}"
}
        

postVpcConfig1() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1
    curl -XPOST $SAFE_ADDR/postVpcConfig1 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delVpcConfig1() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig1 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postVpcConfig2() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2
    curl -XPOST $SAFE_ADDR/postVpcConfig2 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
delVpcConfig2() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig2 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
        

postVpcConfig3() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3
    curl -XPOST $SAFE_ADDR/postVpcConfig3 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
delVpcConfig3() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig3 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
        

postVpcConfig4() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4
    curl -XPOST $SAFE_ADDR/postVpcConfig4 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
delVpcConfig4() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig4 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
        

postVpcConfig5() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4,?Config5,?Value5
    curl -XPOST $SAFE_ADDR/postVpcConfig5 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
delVpcConfig5() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig5 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
        

postInstanceAuthID() {
    local principal=$1
    shift 1
# ?Instance,?AuthID
    curl -XPOST $SAFE_ADDR/postInstanceAuthID -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delInstanceAuthID() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceAuthID -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postInstanceAuthKey() {
    local principal=$1
    shift 1
# ?Instance,?AuthID,?AuthKey
    curl -XPOST $SAFE_ADDR/postInstanceAuthKey -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceAuthKey() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceAuthKey -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceConfig1() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1
    curl -XPOST $SAFE_ADDR/postInstanceConfig1 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceConfig1() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfig1 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceConfig2() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2
    curl -XPOST $SAFE_ADDR/postInstanceConfig2 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
delInstanceConfig2() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfig2 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
        

postInstanceConfig3() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3
    curl -XPOST $SAFE_ADDR/postInstanceConfig3 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
delInstanceConfig3() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfig3 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
        

postInstanceConfig4() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4
    curl -XPOST $SAFE_ADDR/postInstanceConfig4 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
delInstanceConfig4() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfig4 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
        

postInstanceConfig5() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4,?Config5,?Value5
    curl -XPOST $SAFE_ADDR/postInstanceConfig5 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
delInstanceConfig5() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfig5 -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
        

postInstanceCidrConfig() {
    local principal=$1
    shift 1
# ?Instance,?Config,?NetParam
    curl -XPOST $SAFE_ADDR/postInstanceCidrConfig -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceCidrConfig() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceCidrConfig -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceControl() {
    local principal=$1
    shift 1
# ?Host,?Guest
    curl -XPOST $SAFE_ADDR/postInstanceControl -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delInstanceControl() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceControl -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postLinkImageOwner() {
    local principal=$1
    shift 1
# ?Creator,?Image
    curl -XPOST $SAFE_ADDR/postLinkImageOwner -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delLinkImageOwner() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delLinkImageOwner -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postConditionalEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
delConditionalEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delConditionalEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
        

postParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -XPOST $SAFE_ADDR/postParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delParameterizedEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postCluster() {
    local principal=$1
    shift 1
# ?Cluster,?OwnerGuard,?JoinerGuard
    curl -XPOST $SAFE_ADDR/postCluster -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delCluster() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delCluster -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postMembership() {
    local principal=$1
    shift 1
# ?Cluster,?WorkerID
    curl -XPOST $SAFE_ADDR/postMembership -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delMembership -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postAckMembership() {
    local principal=$1
    shift 1
# ?Cluster,?MasterID
    curl -XPOST $SAFE_ADDR/postAckMembership -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delAckMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delAckMembership -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postParameterizedConnection() {
    local principal=$1
    shift 1
# ?Target,?Service,?ConfName
    curl -XPOST $SAFE_ADDR/postParameterizedConnection -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delParameterizedConnection() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delParameterizedConnection -d "{ \"principal\": \"$principal\", \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        
