#!/bin/bash

if [ -z "$SAFE_ADDR" ]; then
    echo ' must set SAFE_ADDR env '
    exit 1
fi


postInstanceSet() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID
    curl -XPOST $SAFE_IP/postInstanceSet -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceSet() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceSet -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postVMInstanceSet() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID,?Cidr
    curl -XPOST $SAFE_IP/postVMInstanceSet -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"]}"
}
delVMInstanceSet() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delVMInstanceSet -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"]}"
}
        

postInstanceAuthID() {
    local principal=$1
    shift 1
# ?Instance,?AuthID
    curl -XPOST $SAFE_IP/postInstanceAuthID -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delInstanceAuthID() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceAuthID -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postInstanceAuthKey() {
    local principal=$1
    shift 1
# ?Instance,?AuthID,?AuthKey
    curl -XPOST $SAFE_IP/postInstanceAuthKey -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceAuthKey() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceAuthKey -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceConfig1() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1
    curl -XPOST $SAFE_IP/postInstanceConfig1 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceConfig1() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceConfig1 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceConfig2() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2
    curl -XPOST $SAFE_IP/postInstanceConfig2 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
delInstanceConfig2() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceConfig2 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
        

postInstanceConfig3() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3
    curl -XPOST $SAFE_IP/postInstanceConfig3 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
delInstanceConfig3() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceConfig3 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"]}"
}
        

postInstanceConfig4() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4
    curl -XPOST $SAFE_IP/postInstanceConfig4 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
delInstanceConfig4() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceConfig4 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"]}"
}
        

postInstanceConfig5() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4,?Config5,?Value5
    curl -XPOST $SAFE_IP/postInstanceConfig5 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
delInstanceConfig5() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceConfig5 -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"]}"
}
        

postInstanceCidrConfig() {
    local principal=$1
    shift 1
# ?Instance,?Config,?NetParam
    curl -XPOST $SAFE_IP/postInstanceCidrConfig -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delInstanceCidrConfig() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceCidrConfig -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postInstanceControl() {
    local principal=$1
    shift 1
# ?Host,?Guest
    curl -XPOST $SAFE_IP/postInstanceControl -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delInstanceControl() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delInstanceControl -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -XPOST $SAFE_IP/postEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -XPOST $SAFE_IP/postConditionalEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
delConditionalEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delConditionalEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"]}"
}
        

postParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -XPOST $SAFE_IP/postParameterizedEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delParameterizedEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delParameterizedEndorsement -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postCluster() {
    local principal=$1
    shift 1
# ?Cluster,?OwnerGuard,?JoinerGuard
    curl -XPOST $SAFE_IP/postCluster -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delCluster() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delCluster -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        

postMembership() {
    local principal=$1
    shift 1
# ?Cluster,?WorkerID
    curl -XPOST $SAFE_IP/postMembership -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delMembership -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postAckMembership() {
    local principal=$1
    shift 1
# ?Cluster,?MasterID
    curl -XPOST $SAFE_IP/postAckMembership -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
delAckMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delAckMembership -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\"]}"
}
        

postParameterizedConnection() {
    local principal=$1
    shift 1
# ?Target,?Service,?ConfName
    curl -XPOST $SAFE_IP/postParameterizedConnection -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
delParameterizedConnection() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_IP/delParameterizedConnection -d "{ \"principal\": $principal, \"otherValues\": [\"${1}\",\"${2}\",\"${3}\"]}"
}
        
